apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: as-app
  labels:
    app: webserver-app
    type: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
        type: front-end
    spec:
      containers:
        - name: webserver
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
