FROM node:14-alpine as build-stage
WORKDIR /app
COPY ./package.json /app/
COPY ./public/ /app/public/
COPY ./src/ /app/src/
RUN yarn install
RUN yarn build

FROM nginx:alpine

COPY --from=build-stage /app/build/ /usr/share/nginx/html
